Repository Mg4145/g3-A-Magical-Code, pull requests merged in 2022-11, with the labels that each got.

#14 Modified huffman
  agents/agent3.py
Labels: codec

#15 Idx based dict
  agents/agent3.py
Labels: MessageTransformer

#17 assertions to detect null deck
  agents/agent3.py
Labels: framework

#16 partial match
  agents/agent3.py
Labels: framework
